Jonathan Develops: Completed UpTime and VersionCheck
Pandarati/CodeU-Summer-2017 pull request #1
Opened 2017-06-06 21:51 UTC by Pandarati

This the code for the completed feature of Up Time and Version Check. This is a code review request.

2017-06-08 18:20 UTC, EveCoulibaly commented on src/codeu/chat/client/commandline/Chat.java
> +
This method only displays the UpTimeServerInfo information. It also needs to display the VersionCheckServerInfo information.

2017-06-08 18:21 UTC, EveCoulibaly commented on src/codeu/chat/client/commandline/Chat.java
> +          //THIS NEEDS TO BE UPDATED
We can update this when we merge all together, ya?

2017-06-08 18:31 UTC, EveCoulibaly commented on src/codeu/chat/client/core/Context.java
> +  }
Because VersionCheck and UpTime have different ServerInfo classes, I believe you would need a getInfo for VersionServerInfo as well.

2017-06-08 18:31 UTC, EveCoulibaly commented on src/codeu/chat/client/core/View.java
> +    /**Gets the Server Information
I like that you have specific comments for your methods! This is great.

2017-06-08 18:33 UTC, EveCoulibaly commented on src/codeu/chat/server/View.java
> +   * Thus, it needed to be defined here.
Love the comments.

2017-06-08 18:41 UTC, EveCoulibaly commented on src/codeu/chat/util/UptimeServerInfo.java
> +// why is this class in the util package? Can we combine the two ServerInfo classes in the
I left this comment before I knew we had to do pull requests but it still stands. I believe the instructions were to put it in the codeu.chat.common package as it is used by both the client and the server.

2017-06-08 18:44 UTC, EveCoulibaly commented on src/codeu/chat/util/UptimeServerInfo.java
> +    public UptimeServerInfo(Uuid version) throws IOException{
This UpTimeServerInfo constructor does not carry a Time value, which I think it needs to. This constructor needs a startTime, maybe add:    this.startTime = Time.now();

2017-06-08 18:49 UTC, EveCoulibaly commented on src/codeu/chat/client/core/View.java
> +            return new UptimeServerInfo(startTime, version);
I would add a comment here as to why this is creating a new UpTimeServerInfo with both a startTime and a version. I am not sure why this is necessary as you have a separate VersionServerInfo class.

2017-06-08 18:55 UTC, EveCoulibaly commented on src/codeu/chat/server/Server.java
> +            Uuid.SERIALIZER.write(out, versionServerInfo.version);
This only writes out the version information, correct? What about the time information? Will you be using the uptimeServerInfo variable to access the time?

2017-06-08 18:57 UTC, EveCoulibaly reviewed
Overall great job! I liked the comments. I also noted that you tried to merge the two mini projects together which is fantastic. I do think, however that you need to go back and make sure the desired information from both mini projects is communicated to the client. Other than that great work!

2017-06-09 15:47 UTC, Pandarati commented on src/codeu/chat/client/core/Context.java
> +  }
Alright, I just combined the two classes, which makes sense. Good catch!

2017-06-09 16:07 UTC, Pandarati commented on src/codeu/chat/client/core/View.java
> +            return new UptimeServerInfo(startTime, version);
Alright, done 👍

2017-06-09 18:23 UTC, Pandarati commented on src/codeu/chat/server/Server.java
> +            Uuid.SERIALIZER.write(out, versionServerInfo.version);
Yes, made changes for time information.

2017-06-09 18:24 UTC, Pandarati commented on src/codeu/chat/util/UptimeServerInfo.java
> +    public UptimeServerInfo(Uuid version) throws IOException{
Will combined the two classes! 👍

2017-06-12 09:15 UTC, nissimnatanov requested changes

2017-06-12 09:15 UTC, nissimnatanov commented on .idea/libraries/_mylyn.xml
> +<component name="libraryTable">
These .idea files are used by local IDE only, and may sometimes contain machine-local info. Since we are going to build, test and run using python, let's just completely ignore these files by adding them to .gitignore. 

The easiest way to do so is:
* one of the team members updates .gitignore to exclude .idea files: simply add **/.idea/** in your main branch's .gitignore file . 
* Everybody: sync .gitignore file
* Everybody: If you already added some IDE specific files, you might need to manually remove those: create temp folder with your pull request branch (do not open in IDE), delete .idea files and submit. Then make sure new pull request has only relevant files.

BTW, see if there are other files too, like .metadata. Please destroy those too using similar logic - those seems to be eclipse related.

2017-06-12 09:15 UTC, nissimnatanov commented on src/codeu/chat/client/core/View.java
> +import codeu.chat.common.*;
https://google.github.io/styleguide/javaguide.html#s3.3-import-statements

No wildcard imports please.

2017-06-12 09:15 UTC, nissimnatanov commented on src/codeu/chat/client/core/View.java
> +    /**Gets the Server Information
:) Indeed. Please just keep the formatting a little nicer: https://google.github.io/styleguide/javaguide.html#s7.1-javadoc-formatting. Also, keep at least one space away from stars :)

2017-06-12 09:15 UTC, nissimnatanov commented on src/codeu/chat/client/core/View.java
> +        //There was a problem with forming the connection
comments between if/else blocks look weird, just move them into else block. Similarly, between try and catch blocks...

2017-06-12 09:15 UTC, nissimnatanov commented on src/codeu/chat/client/core/View.java
> +  public ServerInfo getInfo(){
please add a space before  {

Also, I know many IDEs support auto-formatting. Please check how intellij autoformat works and if it is similar to google style.

2017-06-12 09:15 UTC, nissimnatanov commented on src/codeu/chat/server/Server.java
> +
neh, one line is enough.

2017-06-12 09:15 UTC, nissimnatanov commented on src/codeu/chat/server/View.java
> +   * In BasicView, " public ServerInfo getInfo();" was defined. T
I do not see it in your BasicView ... Is this change still relevant?

2017-06-12 09:15 UTC, nissimnatanov commented on src/codeu/chat/common/ServerInfo.java
> +    public Time startTime;
Please list static fields separate from non-static ones, keeping static ones first.

Also, I would recommend keeping the member fields immutable and hidden:
public final Uuid version;
public final Time startTime;

This way you make the whole class immutable, making it easier to maintain/test in the future.

2017-06-12 09:15 UTC, nissimnatanov commented on src/codeu/chat/common/ServerInfo.java
> +    public ServerInfo(Uuid version) throws IOException{
You do not really need the two constructors with just one arg - please remove those.

2017-06-12 09:15 UTC, nissimnatanov commented on src/codeu/chat/common/ServerInfo.java
> +    public ServerInfo(Time startTime, Uuid version) throws IOException{
After removing two redundant constructors, please leave a comment on two remaining ones in which scenarios are you going to use those (which one is used by server and which one by client).

2017-06-12 09:15 UTC, nissimnatanov commented on src/codeu/chat/server/Server.java
> +            Time.SERIALIZER.write(out, view.getInfo().startTime);
While I generally understand why you take version from one place and startTime from the view, the code looks weird and 'hard to read'. Consider using just view.getInfo() ... you do not really need to create new serverinfo just for the version if you already have it.

2017-06-12 09:15 UTC, nissimnatanov commented on src/codeu/chat/server/Server.java
> +            }catch (Exception ex){
Over-catching is not healthy. Keep your exception catching to declared methods only or to methods that you really expect. Avoid catch generic exceptions such as Exception or Throwable or RuntimeException.

2017-06-13 21:16 UTC, merged