Serena -- Completed Version Check and Tokenized Input
Pandarati/CodeU-Summer-2017 pull request #2
Opened 2017-06-06 23:08 UTC by serenadipity

This is the code for the two mini features Version Check and Tokenized Input. This pull request is for the first code review.

2017-06-08 01:21 UTC, Pandarati requested changes
Everything mostly looks great. I think you just need to be more detailed with your commenting in some areas. Likewise, there are a couple of areas where you can be more descriptive on the user of a variable.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/client/core/Context.java
> +import codeu.chat.common.VersionInfo; //changed from ServerInfo to VersionInfo
I don't think this comment need to be added. In the future, knowing that it was ServerInfo isn't truly relevant, so it could be deleted.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/client/core/View.java
> +import codeu.chat.common.VersionInfo; //changed from ServerInfo to VersionInfo
I don't think this comment need to be added. In the future, knowing that it was ServerInfo isn't truly relevant, so it could be deleted.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/client/core/View.java
> +    Serializers.INTEGER.write(connection.out(), NetworkCode.VERSION_INFO_REQUEST);
Well, the INFO_REQUEST values are still pretty universal for what we're doing. I think it's better off just staying as SERVER_INFO_REQUEST.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/common/NetworkCode.java
> -      public static final int SERVER_INFO_REQUEST = 31;
Well, the INFO_REQUEST values are still pretty universal for what we're doing. I think it's better off just staying as SERVER_INFO_REQUEST.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/common/VersionInfo.java
>    //public final Uuid temp = Uuid.parse(SERVER_VERSION);
This should be deleted since it's not very useful anymore. Too a new coder working on the project, it's just a random comment.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/common/VersionInfo.java
>      	//this.version = Uuid.parse(SERVER_VERSION);
This comment should be deleted this it's not needed.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/common/VersionInfo.java
> +  public VersionInfo(Uuid version) {
Were you getting an error for the UUID version variable?

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/server/Server.java
> +import codeu.chat.common.VersionInfo; //changed from ServerInfo to VersionInfo
I don't think this comment need to be added. In the future, knowing that it was ServerInfo isn't truly relevant, so it could be deleted.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/server/Server.java
> +    this.commands.put(NetworkCode.VERSION_INFO_REQUEST, new Command() {
The INFO_REQUEST constant still represent a "SERVER INFO REQUEST", so it should stay SERVER_INFO_REQUEST. It's not going to be uniquely for "VersionCheck." It's a constant that's representing a VERSION_INFO_REQUEST.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/server/Server.java
> +        Serializers.INTEGER.write(out, NetworkCode.VERSION_INFO_RESPONSE);
The INFO_REQUEST constant still represent a "SERVER INFO REQUEST", so it should stay SERVER_INFO_REQUEST. It's not going to be uniquely for "VersionCheck." It's a constant that's representing a VERSION_INFO_REQUEST.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/client/commandline/Chat.java
> +  for (String token = tokenizer.next(); token != null; token = tokenizer.next()) {
Can you add a comment hear explaining what this for-loop is doing? 👍

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/client/commandline/Chat.java
> +  System.out.println("ERROR");
Can you also paste the error, so it's more specific on what's happening? When actually running the code, if we were to trigger this, it would be more difficult and time consuming to debug.

`System.out.println("ERROR: " + exception);`

I think we all should also use the same format of print errors to the CMD, so we can just follow this basic standard of: `System.out.println("ERROR: " + exception);`

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/client/commandline/Chat.java
> +final String command = args.get(0);
Can you use a more specific naming convention than args? It's pretty difficult to catch on with what's the use of it without referring back to earlier code.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/client/commandline/Chat.java
> +      public void invoke(List<String> args) {
Can you explain in a comment what's going on here, or you can just include a good comment in general that explains what the invoke method is supposed to be doing.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/client/commandline/Chat.java
>      //
Can you have a comment to explain more in-depth what this feature does. I have to read your code in depth to figure it out.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/client/commandline/Chat.java
>      //
I believe you can do this with all the command features, so the programmer can get a good idea of what each command can do without reading too much into the code.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/client/commandline/Panel.java
> +  public boolean handleCommand(String commandName, List<String> args) {
I think you did a excellent job in this area. There are great naming conventions, and there are great comments.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/util/Tokenizer.java
> +import java.io.*;
I think you only want to import the `java.io` classes that are needed. It's supposedly seen as a un-clean approach when importing entire packages, so we only import what we need to use.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/util/Tokenizer.java
> +      // Skip all leading whitespace
I think you can be more specific with the commenting. Instead of:
"// Skip all leading whitespace" 
use something like
"//Skips all of the leading whiespaces that proceeeds the characters.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/util/Tokenizer.java
> +      read();  // ignore the result because we already know that it is a whitespace character
Can you explain more in depth what's happening with this comment and `read()`?
For example: "Goes ahead and reads because we already know that it is a white space character"

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/util/Tokenizer.java
> +   private String readWithNoQuotes() throws IOException {
Can you have a comment above this method that explain what it does? It had a great name, but can you just also include about 2 or 3 sentences explaining?

You can use the multiline comment, so it can also show the `@return` type.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/util/Tokenizer.java
> +   private String readWithQuotes() throws IOException {
Can you have a comment above this method that explain what it does? It had a great name, but can you just also include about 2 or 3 sentences explaining?

You can use the multiline comment, so it can also show the @return type.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/util/Tokenizer.java
> +   private int remaining() {
In a comment, can you comment on what this features does?

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/util/Tokenizer.java
> +   private char peek() throws IOException {
In a comment, can you comment on what this features does?

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/util/Tokenizer.java
> +   private char read() throws IOException {
In a comment, can you comment on what this features does?

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/common/ServerInfo.java
> +  //public final Uuid temp = Uuid.parse(SERVER_VERSION);
This should be deleted since this isn't relevant anymore.

2017-06-08 01:21 UTC, Pandarati commented on src/codeu/chat/common/ServerInfo.java
> +    	//this.version = Uuid.parse(SERVER_VERSION);
This should be deleted since this isn't relevant anymore. It cleans up space and just deletes unnecessary lines.

2017-06-08 01:22 UTC, Pandarati requested changes
There are just some naming convention problems, and there could be some more descriptive comments in certain cases.

2017-06-12 09:36 UTC, nissimnatanov commented on src/codeu/.idea/codeu.iml
> +<?xml version="1.0" encoding="UTF-8"?>
please see my comment to Jonathan on how to handle IntelliJ and other unrelated files using .gitignore.

2017-06-12 09:36 UTC, nissimnatanov commented on src/codeu/chat/client/commandline/Chat.java
> +import java.io.*;
please avoid wildcard imports: https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

2017-06-12 09:36 UTC, nissimnatanov commented on src/codeu/chat/client/commandline/Chat.java
> +final Tokenizer tokenizer = new Tokenizer(line);
indentation missing - please align lines

2017-06-12 09:36 UTC, nissimnatanov commented on src/codeu/chat/common/VersionInfo.java
> +    }
keep an eye on indentation

2017-06-12 09:36 UTC, nissimnatanov commented on src/codeu/chat/common/VersionInfo.java
> +  public VersionInfo(Uuid version) {
since you have two constructors, please elaborate where/when each one is used (client/server)

2017-06-12 09:36 UTC, nissimnatanov commented on src/codeu/chat/common/VersionInfo.java
> +  public Uuid temp = null;
temp should be a local variable inside the function using it.

2017-06-12 09:36 UTC, nissimnatanov commented on src/codeu/chat/util/Tokenizer.java
> +   private String source;
consider making it final - source is not supposed to change

2017-06-12 09:36 UTC, nissimnatanov commented on src/codeu/chat/util/Tokenizer.java
> +   private String source;
also, please move final source arg to the top, grouping final and non-final ones together

2017-06-15 20:14 UTC, closed without merging